version: '3'
services:
  mongodb:
    image: mongo:latest
    container_name: mongo_container
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db # A volume will store the persistent data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=tabashi

volumes:
  mongodb_data:
    driver: local