version: '3'
services:
  mongodb:
    image: mongo:latest
    container_name: mongo_container
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db # A volume will store the persistent data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=tabashi

  springboot-app:
    build:
      context: .
    container_name: springboot_app
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://admin:tabashi@mongodb:27017/AnalysisResult?authSource=admin
    depends_on:
      - mongodb
    command: ["sh", "-c", "sleep 5 && java -jar app.jar"] # Waiting 5 seconds before starting the app, to ensure the mongo started

volumes:
  mongodb_data:
    driver: local
